dist: bionic

services:
  - docker

if: branch = master AND type = push

script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker build -t ${DOCKERHUB_ORG}/pspipe .
  - docker run --rm ${DOCKERHUB_ORG}/pspipe python -c "import camb"

after_success:
  - docker push ${DOCKERHUB_ORG}/pspipe:latest
